name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Package Lambda code
        run: |
          cd lambda_function_directory
          zip -r lambda_code.zip .
        
      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code --function-name <target Lambda function name> --zip-file fileb://lambda_code.zip --region <AWS region>
